apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DB
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: MYSQL_DB
        volumeMounts:
        - name: mysql-init
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-init
        configMap:
          name: mysql-init
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - name: http
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS toktik;
    USE toktik;
    CREATE TABLE IF NOT EXISTS user (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL
    );
    CREATE TABLE IF NOT EXISTS tokens (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(255) UNIQUE NOT NULL,
        token VARCHAR(500) UNIQUE NOT NULL
    );
    CREATE TABLE IF NOT EXISTS video (
        id VARCHAR(255) PRIMARY KEY NOT NULL,
        user_id VARCHAR(255) NOT NULL,
        title VARCHAR(255) NOT NULL
    );
    CREATE TABLE IF NOT EXISTS vls (
        id VARCHAR(255) PRIMARY KEY,
        user_id VARCHAR(255) NOT NULL,
        views INT DEFAULT 0,
        likes INT DEFAULT 0
    );
    CREATE TABLE IF NOT EXISTS comments (
        id INT AUTO_INCREMENT PRIMARY KEY,
        video_id VARCHAR(255) NOT NULL,
        user_id VARCHAR(255) NOT NULL,
        comment VARCHAR(255) NOT NULL,
        video_title VARCHAR(255) NOT NULL,
        timestamp VARCHAR(255) NOT NULL
    );
    CREATE TABLE IF NOT EXISTS notifications (
        id INT AUTO_INCREMENT PRIMARY KEY,
        video_id VARCHAR(255) NOT NULL,
        user_id VARCHAR(255) NOT NULL,
        notification VARCHAR(255) NOT NULL,
        video_title VARCHAR(255) NOT NULL,
        timestamp VARCHAR(255) NOT NULL,
        isRead BOOLEAN NOT NULL
    );
